### ISSUE TITLE
[Server thread/ERROR]: [ChessCraft] Unhandled exception number 2048 occured in onPacketSending(PacketEvent) for ChessCraft java.lang.UnsupportedOperationException: The method getWorld is not supported for temporary players.

### ISSUE THREAD

**Issue by larrycatania** [10becja/ChessCraft#2]
http://pastebin.com/tcnwFtN7  on spigot 1.10.2 latest build with latest protocol dev build

**Comment by 10becja** [comment]
Can you give me any more information? For instance, what actions causes the error to show up?

**Comment by 10becja** [comment]
closed as no response given in over a month.
