### ISSUE TITLE
Download for 1.8

### ISSUE THREAD

**Issue by Peda1996** [10becja/ChessCraft#5]
Could you please provide a Download for your Version of Chesscraft, as i am not able to compile it on my own

**Comment by 10becja** [comment]
Sorry, I've more or less moved on from developing/maintaining minecraft plugins, as I simply don't have enough time for it anymore. Either way 1.8 is rather old, this version wouldn't work anyway (I believe 1.10.2 was the last it ran on, and there were significant changes between 1.8 and 1.10)

You could try downloading from the original author's site on dev.bukkit.org

**Comment by Peda1996** [comment]
Thanks for the fast response
